blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/fedor-i/OpenBioNews/discussions
    about: Ask a question or share how you're using OpenBioNews.
