"""Render a Digest to markdown, HTML or plain text."""

from __future__ import annotations

import html
from collections import OrderedDict

from . import sources
from .models import Cluster, Digest


def _topic_label(topic: str) -> str:
    bundle = sources.BUNDLES.get(topic)
    if bundle:
        return bundle["label"]
    return topic.replace("_", " ").title() if topic else "Other"


def _group(digest: Digest, group_by: str) -> "OrderedDict[str, list[Cluster]]":
    groups: "OrderedDict[str, list[Cluster]]" = OrderedDict()
    if group_by == "topic":
        for cluster in digest.clusters:
            groups.setdefault(cluster.topic, []).append(cluster)
    else:
        groups[""] = list(digest.clusters)
    return groups


def _sources_note(cluster: Cluster) -> str:
    srcs = cluster.sources
    if len(srcs) > 1:
        return f"{srcs[0]} + {len(srcs) - 1} more"
    return srcs[0] if srcs else ""


def render(digest: Digest, fmt: str = "markdown", group_by: str = "topic") -> str:
    if fmt == "html":
        return render_html(digest, group_by)
    if fmt == "text":
        return render_text(digest, group_by)
    return render_markdown(digest, group_by)


def render_markdown(digest: Digest, group_by: str = "topic") -> str:
    date = digest.generated_at.strftime("%A, %d %B %Y")
    out: list[str] = [f"# {digest.title}", "", f"*{date}*"]
    if digest.intro:
        out += ["", digest.intro]
    total = len(digest.clusters)
    out += ["", f"> {total} stories · ~{digest.read_minutes} min read · "
            f"summaries by {digest.backend_label}", ""]

    for topic, clusters in _group(digest, group_by).items():
        if group_by == "topic":
            out.append(f"## {_topic_label(topic)}")
            out.append("")
        for cluster in clusters:
            c = cluster.canonical
            out.append(f"### [{c.title}]({c.link})")
            note = _sources_note(cluster)
            when = cluster.latest.strftime("%d %b %H:%M UTC") if cluster.latest else ""
            meta = " · ".join(x for x in (note, when) if x)
            if meta:
                out.append(f"*{meta}*")
            if cluster.blurb:
                out += ["", cluster.blurb]
            if len(cluster.sources) > 1:
                links = ", ".join(
                    f"[{item.source}]({item.link})"
                    for item in cluster.items
                    if item.source
                )
                out += ["", f"Also: {links}"]
            out.append("")
    out.append("---")
    out.append("*Generated by OpenBioNews.*")
    return "\n".join(out).rstrip() + "\n"


def render_text(digest: Digest, group_by: str = "topic") -> str:
    date = digest.generated_at.strftime("%A, %d %B %Y")
    out: list[str] = [digest.title, date, ""]
    if digest.intro:
        out += [digest.intro, ""]
    out += [
        f"{len(digest.clusters)} stories · ~{digest.read_minutes} min read · "
        f"summaries by {digest.backend_label}",
        "",
    ]
    for topic, clusters in _group(digest, group_by).items():
        if group_by == "topic":
            label = _topic_label(topic)
            out += [label.upper(), "=" * len(label), ""]
        for cluster in clusters:
            c = cluster.canonical
            out.append(f"* {c.title}")
            if cluster.blurb:
                out.append(f"  {cluster.blurb}")
            note = _sources_note(cluster)
            out.append(f"  {note} — {c.link}" if note else f"  {c.link}")
            out.append("")
    out.append("-- Generated by OpenBioNews")
    return "\n".join(out).rstrip() + "\n"


def render_html(digest: Digest, group_by: str = "topic") -> str:
    def esc(s: str) -> str:
        return html.escape(s, quote=True)

    date = digest.generated_at.strftime("%A, %d %B %Y")
    parts: list[str] = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{esc(digest.title)}</title>",
        "<style>",
        ":root{color-scheme:light dark}",
        "body{font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;"
        "max-width:44rem;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fff}",
        "@media (prefers-color-scheme:dark){body{background:#15171a;color:#e6e6e6}"
        "a{color:#8ab4f8}.meta{color:#9aa0a6}.card{border-color:#2c2f33}}",
        "h1{font-size:1.7rem;margin-bottom:.2rem}h2{margin-top:2rem;border-bottom:2px solid #eee;padding-bottom:.3rem}",
        "h3{font-size:1.1rem;margin:.2rem 0}a{color:#1a56db;text-decoration:none}a:hover{text-decoration:underline}",
        ".meta{color:#6b7280;font-size:.85rem;margin:.1rem 0 .4rem}",
        ".card{border:1px solid #eee;border-radius:10px;padding:1rem;margin:.8rem 0}",
        ".sub{font-size:.8rem;color:#6b7280}.count{color:#6b7280;font-size:.9rem}",
        "footer{margin-top:2rem;color:#9aa0a6;font-size:.85rem;border-top:1px solid #eee;padding-top:1rem}",
        "</style></head><body>",
        f"<h1>{esc(digest.title)}</h1>",
        f'<div class="meta">{esc(date)}</div>',
    ]
    if digest.intro:
        parts.append(f"<p>{esc(digest.intro)}</p>")
    parts.append(
        f'<p class="count">{len(digest.clusters)} stories · '
        f"~{digest.read_minutes} min read · "
        f"summaries by {esc(digest.backend_label)}</p>"
    )

    for topic, clusters in _group(digest, group_by).items():
        if group_by == "topic":
            parts.append(f"<h2>{esc(_topic_label(topic))}</h2>")
        for cluster in clusters:
            c = cluster.canonical
            parts.append('<div class="card">')
            parts.append(f'<h3><a href="{esc(c.link)}">{esc(c.title)}</a></h3>')
            note = _sources_note(cluster)
            when = cluster.latest.strftime("%d %b %H:%M UTC") if cluster.latest else ""
            meta = " · ".join(x for x in (note, when) if x)
            if meta:
                parts.append(f'<div class="meta">{esc(meta)}</div>')
            if cluster.blurb:
                parts.append(f"<p>{esc(cluster.blurb)}</p>")
            if len(cluster.sources) > 1:
                links = ", ".join(
                    f'<a href="{esc(item.link)}">{esc(item.source)}</a>'
                    for item in cluster.items
                    if item.source
                )
                parts.append(f'<div class="sub">Also: {links}</div>')
            parts.append("</div>")

    parts.append("<footer>Generated by OpenBioNews.</footer>")
    parts.append("</body></html>")
    return "\n".join(parts) + "\n"
